name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  EB_APPLICATION_NAME: multi-docker
  EB_ENVIRONMENT_NAME: Multi-docker-env
  DEPLOY_PACKAGE: deploy-${{ github.sha }}.zip

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build test Docker image
        run: docker build -t tony5244/docker-multi-react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true tony5244/docker-multi-react-test npm test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker build -t tony5244/multi-client-2 ./client
          docker build -t tony5244/multi-nginx-2 ./nginx
          docker build -t tony5244/multi-server-2 ./server
          docker build -t tony5244/multi-worker-2 ./worker

      - name: Push Docker images
        run: |
          docker push tony5244/multi-client-2
          docker push tony5244/multi-nginx-2
          docker push tony5244/multi-server-2
          docker push tony5244/multi-worker-2

      - name: Create deployment package
        run: |
          zip -r ${{ env.DEPLOY_PACKAGE }} . \
          -x "*.git*" "node_modules/*" "tests/*" "*.md"
